=== decrippter2/decrippter2_data/src/decrippter2_data/schema/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "ref",
    "entries"
  ],
  "properties": {
    "identifiers": {
      "title": "RiPP BGC identifier cross-references",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ncbi_acc": {
          "title": "NCBI Genome accession",
          "type": "string"
        },
        "mibig_acc": {
          "title": "MIBiG BGC accession",
          "$ref": "#/$defs/mibig"
        }
      }
    },
    "compound_name": {
      "title": "Trivial names and synonyms of mature RiPP resulting from precursors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "ripp_class":  {
      "title": "RiPP class name",
      "$ref": "#/$defs/class"
    },
    "ref": {
      "title": "References in DOI format",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/citation"
      }
    },
    "entries": {
      "title": "List of peptide identifiers and composition",
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "complete",
          "core"
        ],
        "properties": {
          "protein_ids": {
            "title": "Collection of protein identifiers",
            "type": "object",
            "properties": {
              "genpept": {
                "title": "Genpept protein accession",
                "$ref": "#/$defs/genpept"
              },
              "uniprot": {
                "title": "UniProt accession",
                "$ref": "#/$defs/uniprot"
              }
            }
          },
          "complete": {
            "title": "Complete precursor sequence",
            "type": "string"
          },
          "leader": {
            "title": "Leader peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "core": {
            "title": "Core peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "follower": {
            "title": "Follower peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "$defs": {
    "citation": {
      "type": "string",
      "pattern": "^doi:10\\."
    },
    "uniprot": {
      "title": "Uniprot ID reference.",
      "type": "string",
      "pattern": "^[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}$"
    },
    "genpept": {
      "title": "GenBank GenPept ID (= protein ID, GenBank gene products)",
      "type": "string",
      "pattern": "^[A-Z]{3}[0-9]{5,7}\\.[0-9]+$"
    },
    "mibig": {
      "title": "MIBiG ID reference",
      "type": "string",
      "pattern": "^BGC\\d{7}$"
    },
    "class": {
      "type": "string",
      "enum": [
        "AIP",
        "Amatoxin",
        "Bacteriocin",
        "Borosin",
        "Bottromycin",
        "Crocagin",
        "Cyanobactin",
        "Cyclotide",
        "Cyptide",
        "Dikaritin",
        "Epipeptide",
        "Glycocin",
        "Graspetide",
        "Guanidinotide",
        "Head-to-tail cyclized peptide",
        "Lanthipeptide",
        "Lasso",
        "Linaridin",
        "Linear azole-containing peptide",
        "Lyciumin",
        "Methanobactin",
        "Microcin",
        "Microviridin",
        "Mycofactocin",
        "N-Formylated TBA",
        "other",
        "Pantocin",
        "Pearlin",
        "Proteusin",
        "Ranthipeptide",
        "Rotapeptide",
        "Ryptide",
        "Sactipeptide",
        "Selidamide",
        "Streptide",
        "Sulfatyrotide",
        "TBA",
        "Thioamitide",
        "Thiopeptide",
        "Ustiloxin"
      ]
    }
  }
}

=== decrippter2/decrippter2_data/data/ripp0000086.json
{
  "identifiers": {
    "ncbi_acc": "AB030831.1",
    "mibig_acc": "BGC0000556"
  },
  "compound_name": [
    "streptin"
  ],
  "ripp_class": "Lanthipeptide",
  "ref": [
    "doi:10.1093/oxfordjournals.jbchem.a002918"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "BAB08162.1",
        "uniprot": "P0C0H8"
      },
      "complete": "MNNTIKDFDLDLKTNKKDTATPYVGSRYLCTPGSCWKLVCFTTTVK",
      "leader": [
        "MNNTIKDFDLDLKTNKKDTATPY"
      ],
      "core": [
        "VGSRYLCTPGSCWKLVCFTTTVK"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000174.json
{
  "identifiers": {
    "ncbi_acc": "CP006259.1",
    "mibig_acc": "BGC0001226"
  },
  "compound_name": [
    "streptocollin"
  ],
  "ripp_class": "Lanthipeptide",
  "ref": [
    "doi:10.1002/cbic.201500377"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "ALA50776.1",
        "uniprot": "A0A0R8Y1S5"
      },
      "complete": "MENQTLELLAHLHALPETDPVDFDGASYSGTCACVGLLTLLNTVCVGISCA",
      "leader": [
        "MENQTLELLAHLHALPETDPVDFDGASY"
      ],
      "core": [
        "SGTCACVGLLTLLNTVCVGISCA"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000116.json
{
      "identifiers": {
            "ncbi_acc": "AF063590.3",
            "mibig_acc": "BGC0000586"
      },
      "compound_name": [
            "microcin E492"
      ],
      "ripp_class": "Microcin",
      "ref": [
            "doi:10.1128/jb.181.1.212-217.1999"
      ],
      "entries": [
            {
                  "protein_ids": {
                        "genpept": "AAD04332.2",
                        "uniprot": "Q9Z4N4"
                  },
                  "complete": "MREISQKDLNLAFGAGETDPNTQLLNDLGNNMAWGAALGAPGGLGSAALGAAGGALQTVGQGLIDHGPVNVPIPVLIGPSWNGSGSGYNSATSSSGSGS",
                  "leader": [
                        "MREISQKDLNLAFGA"
                  ],
                  "core": [
                        "GETDPNTQLLNDLGNNMAWGAALGAPGGLGSAALGAAGGALQTVGQGLIDHGPVNVPIPVLIGPSWNGSGSGYNSATSSSGSGS"
                  ],
                  "follower": [
                        ""
                  ]
            }
      ]
}

=== decrippter2/decrippter2_data/data/ripp0000363.json
{
  "identifiers": {
    "ncbi_acc": "NZ_FOAZ01000001.1",
    "mibig_acc": "BGC0002972"
  },
  "compound_name": [
    "SjiA"
  ],
  "ripp_class": "other",
  "ref": [
    "doi:10.1002/anie.202107192"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "WP_369405959.1"
      },
      "complete": "MSASRDSKSRVTEVRSAVSSRPAPVRLAKRGDAAHSLMLSRVLPDNGVSRLDVAGFQSSI",
      "leader": [
        "TBA"
      ],
      "core": [
        "TBA"
      ],
      "follower": [
        "TBA"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000216.json
{
  "identifiers": {
    "ncbi_acc": "NGTK01000002.1",
    "mibig_acc": "BGC0001639"
  },
  "compound_name": [
    "klebsidin"
  ],
  "ripp_class": "Lasso",
  "ref": [
    "doi:10.1021/acschembio.6b01154"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "OUH62395.1"
      },
      "complete": "MMQQKKNDQKKVTLKKLNKKASKVTRGSDGPIIEFFNPNGVMHYG",
      "leader": [
        "MMQQKKNDQKKVTLKKLNKKASKVTR"
      ],
      "core": [
        "GSDGPIIEFFNPNGVMHYG"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000310.json
{
  "identifiers": {
    "ncbi_acc": "OL539738.1",
    "mibig_acc": "BGC0002631"
  },
  "compound_name": [
    "Myxarylin"
  ],
  "ripp_class": "Cyptide",
  "ref": [
    "doi:10.3390/molecules26247483"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "UID85535.1"
      },
      "complete": "MNYLH",
      "leader": [
        "MN"
      ],
      "core": [
        "YLH"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000350.json
{
  "identifiers": {
    "ncbi_acc": "BMMK00000000.1",
    "mibig_acc": "BGC0002920"
  },
  "compound_name": [
    "longipeptin A",
    "longipeptin B",
    "longipeptin C"
  ],
  "ripp_class": "Lasso",
  "ref": [
    "doi:10.1039/D3SC02380J"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "WP_189061731.1"
      },
      "complete": "MQEQTAYESPALVEVGTFECDTQGWWGANWDGPSGMRD",
      "leader": [
        "MQEQTAYESPALVEVGTFECDTQ"
      ],
      "core": [
        "GWWGANWDGPSGMRD"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000296.json
{
  "identifiers": {
    "ncbi_acc": "MK806443.1",
    "mibig_acc": "BGC0002485"
  },
  "compound_name": [
    "muscoride A",
    "muscoride B"
  ],
  "ripp_class": "Cyanobactin",
  "ref": [
    "doi:10.1021/acschembio.9b00620"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "QGA72599.1",
        "uniprot": "A0A5Q0TX65"
      },
      "complete": "MKPENQKQTRLQPKLSEPTVRVMPGIQLDLSEEELTNGGVGVGGVNASQYGGGDGGVSPSIPSTSGV",
      "leader": [
        "MKPENQKQTRLQPKLSEPTVRVMPGIQLDLSEEELTNGGVGVGGVNASQYGGGDGGVSPS"
      ],
      "core": [
        "IPSTS"
      ],
      "follower": [
        "GV"
      ]
    },
    {
      "protein_ids": {
        "genpept": "QGA72586.1",
        "uniprot": "A0A5Q0TWU3"
      },
      "complete": "MKPENQKQTRLQPKLSEPTVRVMPGIQLDLSEEELTNGGVGVGGVNASQYGGGDGGVSPSVPTTGV",
      "leader": [
        "MKPENQKQTRLQPKLSEPTVRVMPGIQLDLSEEELTNGGVGVGGVNASQYGGGDGGVSPS"
      ],
      "core": [
        "VPTT"
      ],
      "follower": [
        "GV"
      ]
    }
  ]
}
