=== decrippter2/decrippter2_data/src/decrippter2_data/schema/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "ref",
    "entries"
  ],
  "properties": {
    "identifiers": {
      "title": "RiPP BGC identifier cross-references",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ncbi_acc": {
          "title": "NCBI Genome accession",
          "type": "string"
        },
        "mibig_acc": {
          "title": "MIBiG BGC accession",
          "$ref": "#/$defs/mibig"
        }
      }
    },
    "compound_name": {
      "title": "Trivial names and synonyms of mature RiPP resulting from precursors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "ripp_class":  {
      "title": "RiPP class name",
      "$ref": "#/$defs/class"
    },
    "ref": {
      "title": "References in DOI format",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/citation"
      }
    },
    "entries": {
      "title": "List of peptide identifiers and composition",
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "complete",
          "core"
        ],
        "properties": {
          "protein_ids": {
            "title": "Collection of protein identifiers",
            "type": "object",
            "properties": {
              "genpept": {
                "title": "Genpept protein accession",
                "$ref": "#/$defs/genpept"
              },
              "uniprot": {
                "title": "UniProt accession",
                "$ref": "#/$defs/uniprot"
              }
            }
          },
          "complete": {
            "title": "Complete precursor sequence",
            "type": "string"
          },
          "leader": {
            "title": "Leader peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "core": {
            "title": "Core peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "follower": {
            "title": "Follower peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "$defs": {
    "citation": {
      "type": "string",
      "pattern": "^doi:10\\."
    },
    "uniprot": {
      "title": "Uniprot ID reference.",
      "type": "string",
      "pattern": "^[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}$"
    },
    "genpept": {
      "title": "GenBank GenPept ID (= protein ID, GenBank gene products)",
      "type": "string",
      "pattern": "^[A-Z]{3}[0-9]{5,7}\\.[0-9]+$"
    },
    "mibig": {
      "title": "MIBiG ID reference",
      "type": "string",
      "pattern": "^BGC\\d{7}$"
    },
    "class": {
      "type": "string",
      "enum": [
        "AIP",
        "Amatoxin",
        "Bacteriocin",
        "Borosin",
        "Bottromycin",
        "Crocagin",
        "Cyanobactin",
        "Cyclotide",
        "Cyptide",
        "Dikaritin",
        "Epipeptide",
        "Glycocin",
        "Graspetide",
        "Guanidinotide",
        "Head-to-tail cyclized peptide",
        "Lanthipeptide",
        "Lasso",
        "Linaridin",
        "Linear azole-containing peptide",
        "Lyciumin",
        "Methanobactin",
        "Microcin",
        "Microviridin",
        "Mycofactocin",
        "N-Formylated TBA",
        "other",
        "Pantocin",
        "Pearlin",
        "Proteusin",
        "Ranthipeptide",
        "Rotapeptide",
        "Ryptide",
        "Sactipeptide",
        "Selidamide",
        "Streptide",
        "Sulfatyrotide",
        "TBA",
        "Thioamitide",
        "Thiopeptide",
        "Ustiloxin"
      ]
    }
  }
}

=== decrippter2/decrippter2_data/data/ripp0000282.json
{
  "identifiers": {
    "ncbi_acc": "KQ948669.1",
    "mibig_acc": "BGC0002318"
  },
  "compound_name": [
    "canucin A",
    "canucin B"
  ],
  "ripp_class": "Lasso",
  "ref": [
    "doi:10.1021/acschembio.0c00109"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "WP_159064094.1"
      },
      "complete": "MSNSVHNTDRRTAMENMEPETSYEVPELVELGDYDDLTRGVGFPLADFFIHFD",
      "leader": [
        "MSNSVHNTDRRTAMENMEPETSYEVPELVELGDYDDLTR"
      ],
      "core": [
        "GVGFPLADFFIHFD"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000054.json
{
      "identifiers": {
            "ncbi_acc": "Z54312.2",
            "mibig_acc": "BGC0000523"
      },
      "compound_name": [
            "lactocin S"
      ],
      "ripp_class": "Lanthipeptide",
      "ref": [
            "doi:10.1007/BF00399418"
      ],
      "entries": [
            {
                  "protein_ids": {
                        "genpept": "CAA91109.1",
                        "uniprot": "P23826"
                  },
                  "complete": "MKTEKKVLDELSLHASAKMGARDVESSMNADSTPVLASVAVSMELLPTASVLYSDVAGCFKYSAKHHC",
                  "leader": [
                        "MKTEKKVLDELSLHASAKMGARDVESSMNAD"
                  ],
                  "core": [
                        "STPVLASVAVSMELLPTASVLYSDVAGCFKYSAKHHC"
                  ],
                  "follower": [
                        ""
                  ]
            }
      ]
}

=== decrippter2/decrippter2_data/data/ripp0000279.json
{
  "identifiers": {
    "ncbi_acc": "LPCD01000022.1",
    "mibig_acc": "BGC0002312"
  },
  "compound_name": [
    "ubonodin"
  ],
  "ripp_class": "Lasso",
  "ref": [
    "doi:10.1002/cbic.201900707"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "KVR35741.1"
      },
      "complete": "MKHRSTKESFEITCIGDVDVITLMQDASRATMGGDGSIAEYFNRPMHIHDWQIMDSGYYG",
      "leader": [
        "MKHRSTKESFEITCIGDVDVITLMQDASRATM"
      ],
      "core": [
        "GGDGSIAEYFNRPMHIHDWQIMDSGYYG"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000395.json
{
  "identifiers": {
    "ncbi_acc": "GL636070.1",
    "mibig_acc": "BGC0003095"
  },
  "compound_name": [
    "LANII-715"
  ],
  "ripp_class": "Lanthipeptide",
  "ref": [
    "doi:10.1038/s41564-023-01524-6"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "HGD3082990.1"
      },
      "complete": "MNNEDFNLDLVTISKENNSGASTRVTSKSLCTPGCKTGILMTCAIKTATCGCHFG",
      "leader": [
        "MNNEDFNLDLVTISKENNSGASTR"
      ],
      "core": [
        "VTSKSLCTPGCKTGILMTCAIKTATCGCHFG"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000135.json
{
  "identifiers": {
    "ncbi_acc": "JN052143.1",
    "mibig_acc": "BGC0000605"
  },
  "compound_name": [
    "GE37468"
  ],
  "ripp_class": "Thiopeptide",
  "ref": [
    "doi:10.1016/j.chembiol.2014.03.008"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "AEM00614.1",
        "uniprot": "P0C8P9"
      },
      "complete": "MGNNEEYFIDVNDLSIDVFDVVEQGGAVTALTADHGMPEVGASTNCFCYICCSCSSN",
      "leader": [
        "MGNNEEYFIDVNDLSIDVFDVVEQGGAVTALTADHGMPEVGA"
      ],
      "core": [
        "STNCFCYICCSCSS"
      ],
      "follower": [
        "N"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000157.json
{
  "identifiers": {
    "ncbi_acc": "EQ963480.1",
    "mibig_acc": "BGC0000627"
  },
  "compound_name": [
    "ustiloxin B"
  ],
  "ripp_class": "Dikaritin",
  "ref": [
    "doi:10.1016/j.fgb.2014.04.011"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "EED49417.1",
        "uniprot": "B8NM66"
      },
      "complete": "MKLILTLLVSGLCALAAPAAKRDGVEDYAIGIDKRNSVEDYAIGIDKRNSVEDYAIGIDKRNSVEDYAIGIDKRNSVEDYAIGIDKRNTVEDYAIGIDKRNSVEDYAIGIDKRNTVEDYAIGIDKRNSVEDYAIGIDKRNSVEDYAIGIDKRGGSVEDYAIGIDKRNSVEDYAIGIDKRNSVEDYAIGIDKRGSVEDYAIGIDKKRGTVEDYAIGIDKRGGSVEDYAIGIDKRHGGH",
      "leader": [
        "MKLILTLLVSGLCALAAPAAKRDGVED"
      ],
      "core": [
        "YAIG"
      ],
      "follower": [
        "IDKRHGGH"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000043.json
{
      "identifiers": {
            "ncbi_acc": "AF233755.1",
            "mibig_acc": "BGC0000511"
      },
      "compound_name": [
            "ericin S",
            "ericin A"
      ],
      "ripp_class": "Lanthipeptide",
      "ref": [
            "doi:10.1128/jb.184.6.1703-1711.2002"
      ],
      "entries": [
            {
                  "protein_ids": {
                        "genpept": "AAL15569.1",
                        "uniprot": "Q93GH3"
                  },
                  "complete": "MSKFDDFDLDVVKVSKQDSKITPQWKSESVCTPGCVTGVLQTCFLQTITCNCHISK",
                  "leader": [
                        "MSKFDDFDLDVVKVSKQDSKITPQ"
                  ],
                  "core": [
                        "WKSESVCTPGCVTGVLQTCFLQTITCNCHISK"
                  ],
                  "follower": [
                        ""
                  ]
            },
            {
                  "protein_ids": {
                        "genpept": "AAL15567.1",
                        "uniprot": "Q93GH5"
                  },
                  "complete": "MTNMSKFDDFDLDVVKVSKQDSKITPQVLSKSLCTPGCITGPLQTCYLCFPTFAKC",
                  "leader": [
                        "MTNMSKFDDFDLDVVKVSKQDSKITPQ"
                  ],
                  "core": [
                        "VLSKSLCTPGCITGPLQTCYLCFPTFAKC"
                  ],
                  "follower": [
                        ""
                  ]
            }
      ]
}

=== decrippter2/decrippter2_data/data/ripp0000153.json
{
  "identifiers": {
    "ncbi_acc": "AY007251.1",
    "mibig_acc": "BGC0000623"
  },
  "compound_name": [
    "plantaricin W a",
    "plantaricin W b"
  ],
  "ripp_class": "TBA",
  "ref": [
    "doi:10.1099/00221287-147-3-643"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "AAG02566.1",
        "uniprot": "Q9AF68"
      },
      "complete": "MTKTSRRKNAIANYLEPVDEKSINESFGAGDPEARSGIPCTIGAAVAASIAVCPTTKCSKRCGKRKK",
      "leader": [
        "MTKTSRRKNAIANYLEPVDEKSINESFGAGDPEAR"
      ],
      "core": [
        "SGIPCTIGAAVAASIAVCPTTKCSKRCGKRKK"
      ]
    },
    {
      "protein_ids": {
        "genpept": "AAG02567.1",
        "uniprot": "D2KR94"
      },
      "complete": "MKISKIEAQARKDFFKKIDTNSNLLNVNGAKCKWWNISCDLGNNGHVCTLSHECQVSCN",
      "leader": [
        "MKISKIEAQARKDFFKKIDTNSNLLNVNGA"
      ],
      "core": [
        "KCKWWNISCDLGNNGHVCTLSHECQVSCN"
      ]
    }
  ]
}
