=== decrippter2/decrippter2_data/src/decrippter2_data/schema/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "type": "object",
  "required": [
    "ref",
    "entries"
  ],
  "properties": {
    "identifiers": {
      "title": "RiPP BGC identifier cross-references",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ncbi_acc": {
          "title": "NCBI Genome accession",
          "type": "string"
        },
        "mibig_acc": {
          "title": "MIBiG BGC accession",
          "$ref": "#/$defs/mibig"
        }
      }
    },
    "compound_name": {
      "title": "Trivial names and synonyms of mature RiPP resulting from precursors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "ripp_class":  {
      "title": "RiPP class name",
      "$ref": "#/$defs/class"
    },
    "ref": {
      "title": "References in DOI format",
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/citation"
      }
    },
    "entries": {
      "title": "List of peptide identifiers and composition",
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "complete",
          "core"
        ],
        "properties": {
          "protein_ids": {
            "title": "Collection of protein identifiers",
            "type": "object",
            "properties": {
              "genpept": {
                "title": "Genpept protein accession",
                "$ref": "#/$defs/genpept"
              },
              "uniprot": {
                "title": "UniProt accession",
                "$ref": "#/$defs/uniprot"
              }
            }
          },
          "complete": {
            "title": "Complete precursor sequence",
            "type": "string"
          },
          "leader": {
            "title": "Leader peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "core": {
            "title": "Core peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "follower": {
            "title": "Follower peptide sequences",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "$defs": {
    "citation": {
      "type": "string",
      "pattern": "^doi:10\\."
    },
    "uniprot": {
      "title": "Uniprot ID reference.",
      "type": "string",
      "pattern": "^[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}$"
    },
    "genpept": {
      "title": "GenBank GenPept ID (= protein ID, GenBank gene products)",
      "type": "string",
      "pattern": "^[A-Z]{3}[0-9]{5,7}\\.[0-9]+$"
    },
    "mibig": {
      "title": "MIBiG ID reference",
      "type": "string",
      "pattern": "^BGC\\d{7}$"
    },
    "class": {
      "type": "string",
      "enum": [
        "AIP",
        "Amatoxin",
        "Bacteriocin",
        "Borosin",
        "Bottromycin",
        "Crocagin",
        "Cyanobactin",
        "Cyclotide",
        "Cyptide",
        "Dikaritin",
        "Epipeptide",
        "Glycocin",
        "Graspetide",
        "Guanidinotide",
        "Head-to-tail cyclized peptide",
        "Lanthipeptide",
        "Lasso",
        "Linaridin",
        "Linear azole-containing peptide",
        "Lyciumin",
        "Methanobactin",
        "Microcin",
        "Microviridin",
        "Mycofactocin",
        "N-Formylated TBA",
        "other",
        "Pantocin",
        "Pearlin",
        "Proteusin",
        "Ranthipeptide",
        "Rotapeptide",
        "Ryptide",
        "Sactipeptide",
        "Selidamide",
        "Streptide",
        "Sulfatyrotide",
        "TBA",
        "Thioamitide",
        "Thiopeptide",
        "Ustiloxin"
      ]
    }
  }
}

=== decrippter2/decrippter2_data/data/ripp0000010.json
{
      "identifiers": {
            "ncbi_acc": "EU290742.1",
            "mibig_acc": "BGC0000477"
      },
      "compound_name": [
            "patellin 2",
            "patellin 3"
      ],
      "ripp_class": "Cyanobactin",
      "ref": [
            "doi:10.1038/nchembio.84"
      ],
      "entries": [
            {
                  "protein_ids": {
                        "genpept": "ACA04491.1",
                        "uniprot": "B2KYG9"
                  },
                  "complete": "MNKKNILPQLGQPVIRLTAGQLSSQLAELSEEALGGVDASTLPVPTLCSYDGVDASTVPTLCSYDD",
                  "leader": [
                        "MNKKNILPQLGQPVIRLTAGQLSSQLAELSEEALGGVDAS"
                  ],
                  "core": [
                        "TLPVPTLC",
                        "TVPTLC"
                  ],
                  "follower": [
                        "SYDD"
                  ]
            }
      ]
}

=== decrippter2/decrippter2_data/data/ripp0000050.json
{
  "identifiers": {
    "ncbi_acc": "FN178622.1",
    "mibig_acc": "BGC0000519"
  },
  "compound_name": [
    "labyrinthopeptin A2",
    "labyrinthopeptin A1",
    "labyrinthopeptin A3"
  ],
  "ripp_class": "Lanthipeptide",
  "ref": [
    "doi:10.1002/anie.200905909",
    "doi:10.1371/journal.pone.0064010"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "CAX48972.1",
        "uniprot": "C0MP59"
      },
      "complete": "MASILELQDLEVERASSAADSNASVWECCSTGSWVPFTCC",
      "leader": [
        "MASILELQDLEVERASSAAD"
      ],
      "core": [
        "SNASVWECCSTGSWVPFTCC"
      ]
    },
    {
      "protein_ids": {
        "genpept": "CAX48973.1",
        "uniprot": "C0MP60"
      },
      "complete": "MASILELQNLDVEHARGENRSDWSLWECCSTGSLFACC",
      "leader": [
        "MASILELQNLDVEHARGENR"
      ],
      "core": [
        "SDWSLWECCSTGSLFACC"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000036.json
{
  "identifiers": {
    "ncbi_acc": "L37110.1",
    "mibig_acc": "BGC0000504"
  },
  "compound_name": [
    "cytolysin ClyLl",
    "cytolysin ClyLs"
  ],
  "ripp_class": "Lanthipeptide",
  "ref": [
    "doi:10.3390/toxins5050895"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "AAA62648.1",
        "uniprot": "Q52052"
      },
      "complete": "MENLSVVPSFEELSVEEMEAIQGSGDVQAETTPVCAVAATAAASSAACGWVGGGIFTGVTVVVSLKHC",
      "leader": [
        "MENLSVVPSFEELSVEEMEAIQGSGDVQAE"
      ],
      "core": [
        "TTPVCAVAATAAASSAACGWVGGGIFTGVTVVVSLKHC"
      ]
    },
    {
      "protein_ids": {
        "genpept": "AAA62649.1",
        "uniprot": "Q52053"
      },
      "complete": "MLNKENQENYYSNKLELVGPSFEELSLEEMEAIQGSGDVQAETTPACFTIGLGVGALFSAKFC",
      "leader": [
        "MLNKENQENYYSNKLELVGPSFEELSLEEMEAIQGSGDVQAE"
      ],
      "core": [
        "TTPACFTIGLGVGALFSAKFC"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000126.json
{
  "identifiers": {
    "ncbi_acc": "NZ_GG657756.1",
    "mibig_acc": "BGC0000596"
  },
  "compound_name": [
    "SLI-2138"
  ],
  "ripp_class": "N-Formylated TBA",
  "ref": [
    "doi:10.1038/nchembio.684"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "WP_016326148.1"
      },
      "complete": "MQTVVDAHVPSSPGGARRVPHLNSARSCTIMNLLTDILAGLVHFVGWLV",
      "leader": [
        "MQTVVDAHVPSSPGGARRVPHLNSARSCTI"
      ],
      "core": [
        "MNLLTDILAGLVHFVGWLV"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000138.json
{
  "identifiers": {
    "ncbi_acc": "HM236314.1",
    "mibig_acc": "BGC0000608"
  },
  "compound_name": [
    "nocathiacin I"
  ],
  "ripp_class": "Thiopeptide",
  "ref": [
    "doi:10.1007/s10529-010-0460-0"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "ADH93699.1",
        "uniprot": "D7SA58"
      },
      "complete": "MSADLSALNIDSLEISEFLDDSRLEDSEVVAKVMSASCTTCECSCSCSS",
      "leader": [
        "MSADLSALNIDSLEISEFLDDSRLEDSEVVAKVMSA"
      ],
      "core": [
        "SCTTCECSCSCSS"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000059.json
{
      "identifiers": {
            "ncbi_acc": "HM536998.1",
            "mibig_acc": "BGC0000529"
      },
      "compound_name": [
            "microbisporicin A2"
      ],
      "ripp_class": "Lanthipeptide",
      "ref": [
            "doi:10.1016/j.chembiol.2007.11.009"
      ],
      "entries": [
            {
                  "protein_ids": {
                        "genpept": "ADK32554.1",
                        "uniprot": "E2IHB6"
                  },
                  "complete": "MPADILETRTSETEDLLDLDLSIGVEEITAGPAVTSWSLCTPGCTSPGGGSNCSFCC",
                  "leader": [
                        "MPADILETRTSETEDLLDLDLSIGVEEITAGPA"
                  ],
                  "core": [
                        "VTSWSLCTPGCTSPGGGSNCSFCC"
                  ],
                  "follower": [
                        ""
                  ]
            }
      ]
}

=== decrippter2/decrippter2_data/data/ripp0000325.json
{
  "identifiers": {
    "ncbi_acc": "NZ_SBIS02000011.1",
    "mibig_acc": "BGC0002704"
  },
  "compound_name": [
    "archalan b"
  ],
  "ripp_class": "Lanthipeptide",
  "ref": [
    "doi:10.21203/rs.3.rs-1476892/v1"
  ],
  "entries": [
    {
      "protein_ids": {
        "genpept": "WP_162224287.1"
      },
      "complete": "MSVAIQSNDDESLRTEVEAEYKHADHDVPDESKAGLPSASMYSFEHCC",
      "leader": [
        "MSVAIQSNDDESLRTEVEAEYKHADHDVPDESKA"
      ],
      "core": [
        "GLPSASMYSFEHCC"
      ]
    }
  ]
}

=== decrippter2/decrippter2_data/data/ripp0000328.json
{
      "identifiers": {
            "ncbi_acc": "ML179655.1",
            "mibig_acc": "BGC0002746"
      },
      "compound_name": [
            "dendrothelin A"
      ],
      "ripp_class": "Borosin",
      "ref": [
            "doi:10.1038/s41598-021-83106-2"
      ],
      "entries": [
            {
                  "protein_ids": {
                        "genpept": "THU83553.1",
                        "uniprot": "A0A4S8L5C5"
                  },
                  "complete": "MESSTQTKPGSLIVVGTGIESIGQMTLQALSYIEAASKVFYCVIDPATEAFILTKNKNCVDLYQYYDNGKSRMDTYTQMAELMLKEVRNGLDVVGVFYGHPGVFVNPSHRALAIARSEGYQARMLPGVSAEDCLFADLCIDPSNPGCLTYEASDFLIRERPVNVHSHLILFQVGCVGIADFNFSGFDNSKFTILVDRLEQEYGPDHTVVHYIAAMMPHQDPVTDKFTIGQLREPEIAKRVGGVSTFYIPPKARKDINTDIIRLLEFLPAGKVPDKHTQIYPPNQWEPDVPTLPPYGQNEQAAITRLEAHAPPEEYQPLATSKAMTDVMTKLALDPKALAEYKADHRAFAQSVPDLTPQERAALELGDSWAIRCAMKNMPSSLLEAASQSVEEASMNGFPWVIVTGIVGVIGSVVSSA",
                  "leader": [
                        "MESSTQTKPGSLIVVGTGIESIGQMTLQALSYIEAASKVFYCVIDPATEAFILTKNKNCVDLYQYYDNGKSRMDTYTQMAELMLKEVRNGLDVVGVFYGHPGVFVNPSHRALAIARSEGYQARMLPGVSAEDCLFADLCIDPSNPGCLTYEASDFLIRERPVNVHSHLILFQVGCVGIADFNFSGFDNSKFTILVDRLEQEYGPDHTVVHYIAAMMPHQDPVTDKFTIGQLREPEIAKRVGGVSTFYIPPKARKDINTDIIRLLEFLPAGKVPDKHTQIYPPNQWEPDVPTLPPYGQNEQAAITRLEAHAPPEEYQPLATSKAMTDVMTKLALDPKALAEYKADHRAFAQSVPDLTPQERAALELGDSWAIRCAMKNMPSSLLEAASQSVEEASMNGFP"
                  ],
                  "core": [
                        "WVIVTGIVGVIGSVVSSA"
                  ],
                  "follower": [
                        ""
                  ]
            }
      ]
}
